<a href="https://colab.research.google.com/github/joyceliaoo/papyroloreeeee/blob/master/ufos_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import datetime
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline  

pd.options.display.max_columns
pd.options.display.max_rows

60

In [10]:
!git clone https://<usr-name>:<pw>@github.com/joyceliaoo/papyroloreeeee
        
!ls

/bin/bash: usr-name: No such file or directory
papyroloreeeee	sample_data  ufos_cleaned_1.csv

In [3]:
ufos_raw = pd.read_csv('papyroloreeeee/ufo_data/ufo_sighting_data.csv')

ufos_raw.head(10)

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (5,9) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Date_time,city,state/province,country,UFO_shape,length_of_encounter_seconds,described_duration_of_encounter,description,date_documented,latitude,longitude
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700,45 minutes,This event took place in early fall around 194...,4/27/2004,29.8830556,-97.941111
1,10/10/1949 21:00,lackland afb,tx,NaN,light,7200,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...,12/16/2005,29.38421,-98.581082
2,10/10/1955 17:00,chester (uk/england),NaN,gb,circle,20,20 seconds,Green/Orange circular disc over Chester&#44 En...,1/21/2008,53.2,-2.916667
3,10/10/1956 21:00,edna,tx,us,circle,20,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.9783333,-96.645833
4,10/10/1960 20:00,kaneohe,hi,us,light,900,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.4180556,-157.803611
5,10/10/1961 19:00,bristol,tn,us,sphere,300,5 minutes,My father is now 89 my brother 52 the girl wit...,4/27/2007,36.595,-82.188889
6,10/10/1965 21:00,penarth (uk/wales),NaN,gb,circle,180,about 3 mins,penarth uk circle 3mins stayed 30ft above m...,2/14/2006,51.434722,-3.180000
7,10/10/1965 23:45,norwalk,ct,us,disk,1200,20 minutes,A bright orange color changing to reddish colo...,10/2/1999,41.1175,-73.408333
8,10/10/1966 20:00,pell city,al,us,disk,180,3 minutes,Strobe Lighted disk shape object observed clos...,3/19/2009,33.5861111,-86.286111
9,10/10/1966 21:00,live oak,fl,us,disk,120,several minutes,Saucer zaps energy from powerline as my pregna...,5/11/2005,30.2947222,-82.984167

In [4]:
ufos_1 = ufos_raw.drop(columns="description")
ufos_1 = ufos_1.drop(columns="date_documented")
ufos_1 = ufos_1.drop(columns="described_duration_of_encounter")

ufos_1.rename(columns={"Date_time": "date_time"}, inplace=True)
ufos_1.rename(columns={"length_of_encounter_seconds": "len_encounter_secs"}, inplace=True)

ufos_1.columns

Index(['date_time', 'city', 'state/province', 'country', 'UFO_shape',
       'len_encounter_secs', 'latitude', 'longitude'],
      dtype='object')

In [5]:
ufos_1.loc[ufos_1['country'] == 'us']

,date_time,city,state/province,country,UFO_shape,len_encounter_secs,latitude,longitude
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700,29.8830556,-97.941111
3,10/10/1956 21:00,edna,tx,us,circle,20,28.9783333,-96.645833
4,10/10/1960 20:00,kaneohe,hi,us,light,900,21.4180556,-157.803611
5,10/10/1961 19:00,bristol,tn,us,sphere,300,36.595,-82.188889
7,10/10/1965 23:45,norwalk,ct,us,disk,1200,41.1175,-73.408333
8,10/10/1966 20:00,pell city,al,us,disk,180,33.5861111,-86.286111
9,10/10/1966 21:00,live oak,fl,us,disk,120,30.2947222,-82.984167
10,10/10/1968 13:00,hawthorne,ca,us,circle,300,33.9163889,-118.351667
11,10/10/1968 19:00,brevard,nc,us,fireball,180,35.2333333,-82.734444
12,10/10/1970 16:00,bellmore,ny,us,disk,1800,40.6686111,-73.527500
13,10/10/1970 19:00,manchester,ky,us,unknown,180,37.1536111,-83.761944
14,10/10/1971 21:00,lexington,nc,us,oval,30,35.8238889,-80.253611
15,10/10/1972 19:00,harlan county,ky,us,circle,1200,36.8430556,-83.321944
16,10/10/1972 22:30,west bloomfield,mi,us,disk,120,42.5377778,-83.233056
17,10/10/1973 19:00,niantic,ct,us,disk,1800,41.3252778,-72.193611
19,10/10/1974 19:30,hudson,ma,us,other,2700,42.3916667,-71.566667
21,10/10/1974 23:00,hudson,ks,us,light,1200,38.1055556,-98.659722
22,10/10/1975 17:00,north charleston,sc,us,light,360,32.8544444,-79.975000
23,10/10/1976 20:30,washougal,wa,us,oval,60,45.5827778,-122.352222
25,10/10/1977 12:00,san antonio,tx,us,other,30,29.4238889,-98.493333
26,10/10/1977 22:00,louisville,ky,us,light,30,38.2541667,-85.759444
27,10/10/1978 02:00,elmont,ny,us,rectangle,300,40.7008333,-73.713333
28,10/10/1979 00:00,poughkeepsie,ny,us,chevron,900,41.7002778,-73.921389
30,10/10/1979 22:00,san diego,ca,us,oval,180,32.7152778,-117.156389
31,10/10/1979 22:00,security,co,us,unknown,1800,38.7583333,-104.742500
32,10/10/1980 19:00,houston,tx,us,sphere,180,29.7630556,-95.363056
33,10/10/1980 22:00,dallas,tx,us,unknown,300,32.7833333,-96.800000
34,10/10/1980 23:30,manchester,nh,us,light,300,42.9955556,-71.455278
36,10/10/1984 05:00,houston,tx,us,circle,60,29.7630556,-95.363056
37,10/10/1984 12:00,traverse city,mi,us,other,120,44.7630556,-85.620556
...,...,...,...,...,...,...,...,...
80297,9/9/2012 17:00,belton,mo,us,circle,90,38.8119,-94.531667
80298,9/9/2012 19:05,jackson,tn,us,fireball,600,35.6144,-88.813889
80299,9/9/2012 20:00,arcata,ca,us,formation,600,40.8667,-124.081667
80300,9/9/2012 20:00,kannapolis,nc,us,fireball,300,35.4872,-80.621944
80301,9/9/2012 20:00,murfreesboro,tn,us,sphere,180,35.8456,-86.390278
80302,9/9/2012 20:00,wilson,nc,us,light,10800,35.7211,-77.915833
80303,9/9/2012 20:10,elmont,ny,us,circle,600,40.7008,-73.713333
80304,9/9/2012 20:30,mt. juliet,tn,us,light,120,36.2,-86.518611
80305,9/9/2012 20:30,ventura,ca,us,chevron,900,34.2783,-119.292222
80306,9/9/2012 20:52,south jordan,ut,us,circle,10,40.5622,-111.928889
80307,9/9/2012 21:00,elkhart,in,us,oval,600,41.6819,-85.976667
80308,9/9/2012 21:00,new york city (brooklyn),ny,us,light,1290,40.7142,-74.006389
80309,9/9/2012 21:00,pawleys island,sc,us,oval,60,33.4331,-79.121667
80310,9/9/2012 21:00,ventura,ca,us,circle,300,34.2783,-119.292222
80311,9/9/2012 21:55,charleston,sc,us,flash,900,32.7764,-79.931111
80312,9/9/2012 23:00,gainesville,ga,us,light,5,34.2978,-83.824167
80313,9/9/2013 00:15,norfolk,va,us,unknown,1,36.8467,-76.285556
80314,9/9/2013 01:50,buffalo (west of; on highway 90 west),ny,us,triangle,180,42.8864,-78.878611
80315,9/9/2013 03:00,struthers,oh,us,unknown,120,41.0525,-80.608056
80316,9/9/2013 09:51,san diego,ca,us,light,4,32.7153,-117.156389
80317,9/9/2013 12:34,cedar park,tx,us,cigar,8,30.505,-97.820000
80320,9/9/2013 20:20,tuscaloosa,al,us,fireball,60,33.2097,-87.569167
80321,9/9/2013 20:21,clarksville,tn,us,fireball,3,36.5297,-87.359444
80323,9/9/2013 21:00,gainesville,fl,us,triangle,60,29.6514,-82.325000
80326,9/9/2013 21:00,woodstock,ga,us,sphere,20,34.1014,-84.519444
80327,9/9/2013 21:15,nashville,tn,us,light,600,36.1658,-86.784444
80328,9/9/2013 22:00,boise,id,us,circle,1200,43.6136,-116.202500
80329,9/9/2013 22:00,napa,ca,us,other,1200,38.2972,-122.284444
80330,9/9/2013 22:20,vienna,va,us,circle,5,38.9011,-77.265556
80331,9/9/2013 23:00,edmond,ok,us,cigar,1020,35.6528,-97.477778

In [6]:
ufos_1.loc[(ufos_1['city'].isin(['uk'])) & (ufos_1['country'].hasnans)]  = "gb"
ufos_1

ufos_1.loc[(ufos_1['city'].isin(['canada'])) & (ufos_1['country'].hasnans)]  = "ca"
ufos_1

#ufos_1.loc[(ufos_1['city'].isin(['canada'])) & (ufos_1['country'].hasnans)]  = "ca"
#ufos_1.loc[ufos_1['city'].isin(['canada'])]

,date_time,city,state/province,country,UFO_shape,len_encounter_secs,latitude,longitude
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700,29.8830556,-97.9411
1,10/10/1949 21:00,lackland afb,tx,NaN,light,7200,29.38421,-98.5811
2,10/10/1955 17:00,chester (uk/england),NaN,gb,circle,20,53.2,-2.91667
3,10/10/1956 21:00,edna,tx,us,circle,20,28.9783333,-96.6458
4,10/10/1960 20:00,kaneohe,hi,us,light,900,21.4180556,-157.804
5,10/10/1961 19:00,bristol,tn,us,sphere,300,36.595,-82.1889
6,10/10/1965 21:00,penarth (uk/wales),NaN,gb,circle,180,51.434722,-3.18
7,10/10/1965 23:45,norwalk,ct,us,disk,1200,41.1175,-73.4083
8,10/10/1966 20:00,pell city,al,us,disk,180,33.5861111,-86.2861
9,10/10/1966 21:00,live oak,fl,us,disk,120,30.2947222,-82.9842
10,10/10/1968 13:00,hawthorne,ca,us,circle,300,33.9163889,-118.352
11,10/10/1968 19:00,brevard,nc,us,fireball,180,35.2333333,-82.7344
12,10/10/1970 16:00,bellmore,ny,us,disk,1800,40.6686111,-73.5275
13,10/10/1970 19:00,manchester,ky,us,unknown,180,37.1536111,-83.7619
14,10/10/1971 21:00,lexington,nc,us,oval,30,35.8238889,-80.2536
15,10/10/1972 19:00,harlan county,ky,us,circle,1200,36.8430556,-83.3219
16,10/10/1972 22:30,west bloomfield,mi,us,disk,120,42.5377778,-83.2331
17,10/10/1973 19:00,niantic,ct,us,disk,1800,41.3252778,-72.1936
18,10/10/1973 23:00,bermuda nas,NaN,NaN,light,20,32.364167,-64.6786
19,10/10/1974 19:30,hudson,ma,us,other,2700,42.3916667,-71.5667
20,10/10/1974 21:30,cardiff (uk/wales),NaN,gb,disk,1200,51.5,-3.2
21,10/10/1974 23:00,hudson,ks,us,light,1200,38.1055556,-98.6597
22,10/10/1975 17:00,north charleston,sc,us,light,360,32.8544444,-79.975
23,10/10/1976 20:30,washougal,wa,us,oval,60,45.5827778,-122.352
24,10/10/1976 22:00,stoke mandeville (uk/england),NaN,gb,cigar,3,51.783333,-0.783333
25,10/10/1977 12:00,san antonio,tx,us,other,30,29.4238889,-98.4933
26,10/10/1977 22:00,louisville,ky,us,light,30,38.2541667,-85.7594
27,10/10/1978 02:00,elmont,ny,us,rectangle,300,40.7008333,-73.7133
28,10/10/1979 00:00,poughkeepsie,ny,us,chevron,900,41.7002778,-73.9214
29,10/10/1979 22:00,saddle lake (canada),ab,NaN,triangle,270,53.970571,-111.69
...,...,...,...,...,...,...,...,...
80302,9/9/2012 20:00,wilson,nc,us,light,10800,35.7211,-77.9158
80303,9/9/2012 20:10,elmont,ny,us,circle,600,40.7008,-73.7133
80304,9/9/2012 20:30,mt. juliet,tn,us,light,120,36.2,-86.5186
80305,9/9/2012 20:30,ventura,ca,us,chevron,900,34.2783,-119.292
80306,9/9/2012 20:52,south jordan,ut,us,circle,10,40.5622,-111.929
80307,9/9/2012 21:00,elkhart,in,us,oval,600,41.6819,-85.9767
80308,9/9/2012 21:00,new york city (brooklyn),ny,us,light,1290,40.7142,-74.0064
80309,9/9/2012 21:00,pawleys island,sc,us,oval,60,33.4331,-79.1217
80310,9/9/2012 21:00,ventura,ca,us,circle,300,34.2783,-119.292
80311,9/9/2012 21:55,charleston,sc,us,flash,900,32.7764,-79.9311
80312,9/9/2012 23:00,gainesville,ga,us,light,5,34.2978,-83.8242
80313,9/9/2013 00:15,norfolk,va,us,unknown,1,36.8467,-76.2856
80314,9/9/2013 01:50,buffalo (west of; on highway 90 west),ny,us,triangle,180,42.8864,-78.8786
80315,9/9/2013 03:00,struthers,oh,us,unknown,120,41.0525,-80.6081
80316,9/9/2013 09:51,san diego,ca,us,light,4,32.7153,-117.156
80317,9/9/2013 12:34,cedar park,tx,us,cigar,8,30.505,-97.82
80318,9/9/2013 13:10,calmar (canada),ab,ca,unknown,90,53.25,-113.783
80319,9/9/2013 20:15,clifton,nj,NaN,other,3600,40.8584,-74.1638
80320,9/9/2013 20:20,tuscaloosa,al,us,fireball,60,33.2097,-87.5692
80321,9/9/2013 20:21,clarksville,tn,us,fireball,3,36.5297,-87.3594
80322,9/9/2013 21:00,aleksandrow (poland),NaN,NaN,light,15,50.4658,22.8918
80323,9/9/2013 21:00,gainesville,fl,us,triangle,60,29.6514,-82.325
80324,9/9/2013 21:00,hamstead (hollyridge),nc,NaN,light,120,34.3676,-77.7105
80325,9/9/2013 21:00,milton (canada),on,ca,fireball,180,46.3,-63.2167
80326,9/9/2013 21:00,woodstock,ga,us,sphere,20,34.1014,-84.5194
80327,9/9/2013 21:15,nashville,tn,us,light,600,36.1658,-86.7844
80328,9/9/2013 22:00,boise,id,us,circle,1200,43.6136,-116.203
80329,9/9/2013 22:00,napa,ca,us,other,1200,38.2972,-122.284
80330,9/9/2013 22:20,vienna,va,us,circle,5,38.9011,-77.2656
80331,9/9/2013 23:00,edmond,ok,us,cigar,1020,35.6528,-97.4778

In [7]:
ufos_1

,date_time,city,state/province,country,UFO_shape,len_encounter_secs,latitude,longitude
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700,29.8830556,-97.9411
1,10/10/1949 21:00,lackland afb,tx,NaN,light,7200,29.38421,-98.5811
2,10/10/1955 17:00,chester (uk/england),NaN,gb,circle,20,53.2,-2.91667
3,10/10/1956 21:00,edna,tx,us,circle,20,28.9783333,-96.6458
4,10/10/1960 20:00,kaneohe,hi,us,light,900,21.4180556,-157.804
5,10/10/1961 19:00,bristol,tn,us,sphere,300,36.595,-82.1889
6,10/10/1965 21:00,penarth (uk/wales),NaN,gb,circle,180,51.434722,-3.18
7,10/10/1965 23:45,norwalk,ct,us,disk,1200,41.1175,-73.4083
8,10/10/1966 20:00,pell city,al,us,disk,180,33.5861111,-86.2861
9,10/10/1966 21:00,live oak,fl,us,disk,120,30.2947222,-82.9842
10,10/10/1968 13:00,hawthorne,ca,us,circle,300,33.9163889,-118.352
11,10/10/1968 19:00,brevard,nc,us,fireball,180,35.2333333,-82.7344
12,10/10/1970 16:00,bellmore,ny,us,disk,1800,40.6686111,-73.5275
13,10/10/1970 19:00,manchester,ky,us,unknown,180,37.1536111,-83.7619
14,10/10/1971 21:00,lexington,nc,us,oval,30,35.8238889,-80.2536
15,10/10/1972 19:00,harlan county,ky,us,circle,1200,36.8430556,-83.3219
16,10/10/1972 22:30,west bloomfield,mi,us,disk,120,42.5377778,-83.2331
17,10/10/1973 19:00,niantic,ct,us,disk,1800,41.3252778,-72.1936
18,10/10/1973 23:00,bermuda nas,NaN,NaN,light,20,32.364167,-64.6786
19,10/10/1974 19:30,hudson,ma,us,other,2700,42.3916667,-71.5667
20,10/10/1974 21:30,cardiff (uk/wales),NaN,gb,disk,1200,51.5,-3.2
21,10/10/1974 23:00,hudson,ks,us,light,1200,38.1055556,-98.6597
22,10/10/1975 17:00,north charleston,sc,us,light,360,32.8544444,-79.975
23,10/10/1976 20:30,washougal,wa,us,oval,60,45.5827778,-122.352
24,10/10/1976 22:00,stoke mandeville (uk/england),NaN,gb,cigar,3,51.783333,-0.783333
25,10/10/1977 12:00,san antonio,tx,us,other,30,29.4238889,-98.4933
26,10/10/1977 22:00,louisville,ky,us,light,30,38.2541667,-85.7594
27,10/10/1978 02:00,elmont,ny,us,rectangle,300,40.7008333,-73.7133
28,10/10/1979 00:00,poughkeepsie,ny,us,chevron,900,41.7002778,-73.9214
29,10/10/1979 22:00,saddle lake (canada),ab,NaN,triangle,270,53.970571,-111.69
...,...,...,...,...,...,...,...,...
80302,9/9/2012 20:00,wilson,nc,us,light,10800,35.7211,-77.9158
80303,9/9/2012 20:10,elmont,ny,us,circle,600,40.7008,-73.7133
80304,9/9/2012 20:30,mt. juliet,tn,us,light,120,36.2,-86.5186
80305,9/9/2012 20:30,ventura,ca,us,chevron,900,34.2783,-119.292
80306,9/9/2012 20:52,south jordan,ut,us,circle,10,40.5622,-111.929
80307,9/9/2012 21:00,elkhart,in,us,oval,600,41.6819,-85.9767
80308,9/9/2012 21:00,new york city (brooklyn),ny,us,light,1290,40.7142,-74.0064
80309,9/9/2012 21:00,pawleys island,sc,us,oval,60,33.4331,-79.1217
80310,9/9/2012 21:00,ventura,ca,us,circle,300,34.2783,-119.292
80311,9/9/2012 21:55,charleston,sc,us,flash,900,32.7764,-79.9311
80312,9/9/2012 23:00,gainesville,ga,us,light,5,34.2978,-83.8242
80313,9/9/2013 00:15,norfolk,va,us,unknown,1,36.8467,-76.2856
80314,9/9/2013 01:50,buffalo (west of; on highway 90 west),ny,us,triangle,180,42.8864,-78.8786
80315,9/9/2013 03:00,struthers,oh,us,unknown,120,41.0525,-80.6081
80316,9/9/2013 09:51,san diego,ca,us,light,4,32.7153,-117.156
80317,9/9/2013 12:34,cedar park,tx,us,cigar,8,30.505,-97.82
80318,9/9/2013 13:10,calmar (canada),ab,ca,unknown,90,53.25,-113.783
80319,9/9/2013 20:15,clifton,nj,NaN,other,3600,40.8584,-74.1638
80320,9/9/2013 20:20,tuscaloosa,al,us,fireball,60,33.2097,-87.5692
80321,9/9/2013 20:21,clarksville,tn,us,fireball,3,36.5297,-87.3594
80322,9/9/2013 21:00,aleksandrow (poland),NaN,NaN,light,15,50.4658,22.8918
80323,9/9/2013 21:00,gainesville,fl,us,triangle,60,29.6514,-82.325
80324,9/9/2013 21:00,hamstead (hollyridge),nc,NaN,light,120,34.3676,-77.7105
80325,9/9/2013 21:00,milton (canada),on,ca,fireball,180,46.3,-63.2167
80326,9/9/2013 21:00,woodstock,ga,us,sphere,20,34.1014,-84.5194
80327,9/9/2013 21:15,nashville,tn,us,light,600,36.1658,-86.7844
80328,9/9/2013 22:00,boise,id,us,circle,1200,43.6136,-116.203
80329,9/9/2013 22:00,napa,ca,us,other,1200,38.2972,-122.284
80330,9/9/2013 22:20,vienna,va,us,circle,5,38.9011,-77.2656
80331,9/9/2013 23:00,edmond,ok,us,cigar,1020,35.6528,-97.4778

In [0]:
ufos_1.to_csv("ufos_cleaned_1.csv", index=False, encoding='utf8')

from google.colab import files

files.download('ufos_cleaned_1.csv')